"""Opcode and status tables copied from Wireshark's packet-couchbase.c.

This file is data. analyze_capture counts.
"""

# Wireshark client opcode labels from packet-couchbase.c (client_opcode_vals).
# The field reference lists couchbase.opcode but not these values.
OPCODES = {
    0x00: 'Get',
    0x01: 'Set',
    0x02: 'Add',
    0x03: 'Replace',
    0x04: 'Delete',
    0x05: 'Increment',
    0x06: 'Decrement',
    0x07: 'Quit',
    0x08: 'Flush',
    0x09: 'Get Quietly',
    0x0A: 'NOOP',
    0x0B: 'Version',
    0x0C: 'Get Key',
    0x0D: 'Get Key Quietly',
    0x0E: 'Append',
    0x0F: 'Prepend',
    0x10: 'Statistics',
    0x11: 'Set Quietly',
    0x12: 'Add Quietly',
    0x13: 'Replace Quietly',
    0x14: 'Delete Quietly',
    0x15: 'Increment Quietly',
    0x16: 'Decrement Quietly',
    0x17: 'Quit Quietly',
    0x18: 'Flush Quietly',
    0x19: 'Append Quietly',
    0x1A: 'Prepend Quietly',
    0x1B: 'Verbosity',
    0x1C: 'Touch',
    0x1D: 'Get and Touch',
    0x1E: 'Gat and Touch Quietly',
    0x1F: 'Hello',
    0x20: 'List SASL Mechanisms',
    0x21: 'SASL Authenticate',
    0x22: 'SASL Step',
    0x23: 'IOCTL Get',
    0x24: 'IOCTL Set',
    0x25: 'Config Validate',
    0x26: 'Config Reload',
    0x27: 'Audit Put',
    0x28: 'Audit Config Reload',
    0x29: 'Shutdown',
    0x2D: 'Set Active Encryption Keys',
    0x2E: 'Prune Encryption Keys',
    0x30: 'Range Get',
    0x31: 'Range Set',
    0x32: 'Range Set Quietly',
    0x33: 'Range Append',
    0x34: 'Range Append Quietly',
    0x35: 'Range Prepend',
    0x36: 'Range Prepend Quietly',
    0x37: 'Range Delete',
    0x38: 'Range Delete Quietly',
    0x39: 'Range Increment',
    0x3A: 'Range Increment Quietly',
    0x3B: 'Range Decrement',
    0x3C: 'Range Decrement Quietly',
    0x3D: 'Set VBucket',
    0x3E: 'Get VBucket',
    0x3F: 'Delete VBucket',
    0x40: 'TAP Connect',
    0x41: 'TAP Mutation',
    0x42: 'TAP Delete',
    0x43: 'TAP Flush',
    0x44: 'TAP Opaque',
    0x45: 'TAP VBucket Set',
    0x46: 'TAP Checkpoint Start',
    0x47: 'TAP Checkpoint End',
    0x48: 'Get All VBucket Seqnos',
    0x49: 'GetEx',
    0x4A: 'GetEx Replica',
    0x50: 'DCP Open Connection',
    0x51: 'DCP Add Stream',
    0x52: 'DCP Close Stream',
    0x53: 'DCP Stream Request',
    0x54: 'DCP Get Failover Log',
    0x55: 'DCP Stream End',
    0x56: 'DCP Snapshot Marker',
    0x57: 'DCP (Key) Mutation',
    0x58: 'DCP (Key) Deletion',
    0x59: 'DCP (Key) Expiration',
    0x5A: 'DCP Flush',
    0x5B: 'DCP Set VBucket State',
    0x5C: 'DCP NOOP',
    0x5D: 'DCP Buffer Acknowledgement',
    0x5E: 'DCP Control',
    0x5F: 'DCP System Event',
    0x60: 'DCP Prepare',
    0x61: 'DCP Seqno Acknowledgement',
    0x62: 'DCP Commit',
    0x63: 'DCP Abort',
    0x64: 'DCP Seqno Advanced',
    0x65: 'DCP Out of Sequence Order Snapshot',
    0x66: 'DCP Cache Transfer',
    0x67: 'DCP Cache Transfer End',
    0x70: 'Get Fusion Storage Snapshot',
    0x71: 'Release Fusion Storage Snapshot',
    0x72: 'Mount Fusion VBucket',
    0x73: 'Unmount Fusion VBucket',
    0x74: 'Sync Fusion Logstore',
    0x75: 'Start Fusion Uploader',
    0x76: 'Stop Fusion Uploader',
    0x77: 'Delete Fusion Namespace',
    0x78: 'Get Fusion Namespaces',
    0x80: 'Stop Persistence',
    0x81: 'Start Persistence',
    0x82: 'Set Parameter',
    0x83: 'Get Replica',
    0x85: 'Create Bucket',
    0x86: 'Delete Bucket',
    0x87: 'List Buckets',
    0x88: 'Expand Bucket',
    0x89: 'Select Bucket',
    0x90: 'Start Replication',
    0x91: 'Observe Sequence Number',
    0x92: 'Observe',
    0x93: 'Evict Key',
    0x94: 'Get Locked',
    0x95: 'Unlock Key',
    0x96: 'Sync',
    0x97: 'Last Closed Checkpoint',
    0x98: 'Restore File',
    0x99: 'Restore Abort',
    0x9A: 'Restore Complete',
    0x9B: 'Online Update Start',
    0x9C: 'Online Update Complete',
    0x9D: 'Online Update Revert',
    0x9E: 'Deregister TAP Client',
    0x9F: 'Reset Replication Chain',
    0xA0: 'Get Meta',
    0xA1: 'Get Meta Quietly',
    0xA2: 'Set with Meta',
    0xA3: 'Set with Meta Quietly',
    0xA4: 'Add with Meta',
    0xA5: 'Add with Meta Quietly',
    0xA6: 'Snapshot VBuckets States',
    0xA7: 'VBucket Batch Count',
    0xA8: 'Delete with Meta',
    0xA9: 'Delete with Meta Quietly',
    0xAA: 'Create Checkpoint',
    0xAC: 'Notify VBucket Update',
    0xAD: 'Enable Traffic',
    0xAE: 'Disable Traffic',
    0xAF: 'Ifconfig',
    0xB0: 'Change VBucket Filter',
    0xB1: 'Checkpoint Persistence',
    0xB2: 'Return Meta',
    0xB3: 'Compact Database',
    0xB4: 'Set Cluster Config',
    0xB5: 'Get Cluster Config',
    0xB6: 'Get Random Key',
    0xB7: 'Seqno Persistence',
    0xB8: 'Get Keys',
    0xB9: "Set Collection's Manifest",
    0xBA: "Get Collection's Manifest",
    0xBB: 'Get Collection ID',
    0xBC: 'Get Scope ID',
    0xC1: 'Set Drift Counter State',
    0xC2: 'Get Adjusted Time',
    0xC5: 'Subdoc Get',
    0xC6: 'Subdoc Exists',
    0xC7: 'Subdoc Dictionary Add',
    0xC8: 'Subdoc Dictionary Upsert',
    0xC9: 'Subdoc Delete',
    0xCA: 'Subdoc Replace',
    0xCB: 'Subdoc Array Push Last',
    0xCC: 'Subdoc Array Push First',
    0xCD: 'Subdoc Array Insert',
    0xCE: 'Subdoc Array Add Unique',
    0xCF: 'Subdoc Counter',
    0xD0: 'Subdoc Multipath Lookup',
    0xD1: 'Subdoc Multipath Mutation',
    0xD2: 'Subdoc Get Count',
    0xD3: 'Subdoc Replace Body With Xattr',
    0xDA: 'RangeScan Create',
    0xDB: 'RangeScan Continue',
    0xDC: 'RangeScan Cancel',
    0xE0: 'Prepare Snapshot',
    0xE1: 'Release Snapshot',
    0xE2: 'Download Snapshot',
    0xE3: 'Get File Fragment',
    0xF0: 'Scrub',
    0xF1: 'isasl Refresh',
    0xF2: 'SSL Certificates Refresh',
    0xF3: 'Internal Timer Control',
    0xF4: 'Set Control Token',
    0xF5: 'Get Control Token',
    0xF6: 'Update External User Permissions',
    0xF7: 'RBAC Refresh',
    0xF8: 'Auth Provider',
    0xFB: 'Drop Privilege',
    0xFC: 'Adjust Timeofday',
    0xFD: 'EWOULDBLOCK Control',
    0xFE: 'Get Error Map',
}


# DCP is the in-cluster replication stream. Meta commands are XDCR.
# Stored as the lowercase hex text tshark prints, so a membership test
# does not parse the opcode again.
CLUSTER_OPCODES = {f"0x{code:02x}" for code in range(0x50, 0x68)} | {
    "0x48", "0xa0", "0xa1", "0xa2", "0xa3", "0xa4", "0xa5", "0xa8",
}


# Plain descriptions for the commands people meet on port 11210.
# Names stay as Wireshark prints them. The chart tooltips show these sentences.
OPCODE_DESCRIPTIONS = {
    0x00: "Retrieves a document.",
    0x01: "Stores a document unconditionally.",
    0x02: "Stores a document only if it does not exist.",
    0x03: "Stores a document only if it already exists.",
    0x04: "Removes a document.",
    0x05: "Increments a numeric counter.",
    0x06: "Decrements a numeric counter.",
    0x07: "Closes the connection.",
    0x08: "Flushes the bucket, when that is enabled.",
    0x09: "Quiet Get. No response when the key does not exist.",
    0x0A: "No-op. Keep-alive.",
    0x0B: "Gets the server version.",
    0x0C: "Get, and return the key in the response.",
    0x0D: "Quiet Get, and return the key.",
    0x0E: "Appends data to an existing document.",
    0x0F: "Prepends data to an existing document.",
    0x10: "Retrieves server statistics. Key vbucket-seqno is the DCP high-seqno poll.",
    0x11: "Quiet Set. No response on success.",
    0x12: "Quiet Add. No response on success.",
    0x13: "Quiet Replace. No response on success.",
    0x14: "Quiet Delete. No response on success.",
    0x15: "Quiet Increment. No response on success.",
    0x16: "Quiet Decrement. No response on success.",
    0x17: "Quiet Quit. No response on success.",
    0x18: "Quiet Flush. No response on success.",
    0x19: "Quiet Append. No response on success.",
    0x1A: "Quiet Prepend. No response on success.",
    0x1B: "Sets logging verbosity.",
    0x1C: "Updates a document's expiration time.",
    0x1D: "Get and Touch. Retrieves the document and updates its expiration.",
    0x1E: "Quiet Get and Touch.",
    0x1F: "Hello. Client capability negotiation.",
    0x20: "Lists supported SASL authentication mechanisms.",
    0x21: "Starts SASL authentication.",
    0x22: "Continues SASL authentication.",
    0x23: "IOCTL Get.",
    0x24: "IOCTL Set.",
    0x25: "Validates configuration.",
    0x26: "Reloads configuration.",
    0x27: "Writes an audit event.",
    0x28: "Reloads audit configuration.",
    0x29: "Shuts the server down.",
    0x30: "Replica Get.",
    0x31: "Replica Set.",
    0x32: "Quiet Replica Set.",
    0x33: "Replica Append.",
    0x34: "Quiet Replica Append.",
    0x35: "Replica Prepend.",
    0x36: "Quiet Replica Prepend.",
    0x37: "Replica Delete.",
    0x38: "Quiet Replica Delete.",
    0x39: "Replica Increment.",
    0x3A: "Quiet Replica Increment.",
    0x3B: "Replica Decrement.",
    0x3C: "Quiet Replica Decrement.",
    0x3D: "Sets a vBucket state.",
    0x3E: "Reads a vBucket state.",
    0x3F: "Deletes a vBucket.",
    0x40: "TAP Connect. Legacy replication.",
    0x41: "TAP Mutation. Legacy replication.",
    0x42: "TAP Delete. Legacy replication.",
    0x43: "TAP Flush. Legacy replication.",
    0x44: "TAP Opaque. Legacy replication.",
    0x45: "TAP vBucket set. Legacy replication.",
    0x46: "TAP checkpoint start. Legacy replication.",
    0x47: "TAP checkpoint end. Legacy replication.",
    0x50: "DCP Open. Starts a streaming connection.",
    0x51: "DCP add stream.",
    0x52: "DCP close stream.",
    0x53: "DCP stream request. Its opaque is copied onto every later message for that stream.",
    0x54: "DCP get failover log.",
    0x55: "DCP stream end. The consumer does not reply.",
    0x56: "DCP snapshot marker. A reply is required only when the ack flag 0x08 is set.",
    0x57: "DCP mutation. The consumer does not reply. Flow control is a later buffer ack.",
    0x58: "DCP deletion. The consumer does not reply.",
    0x59: "DCP expiration. The consumer does not reply.",
    0x5A: "DCP flush.",
    0x5B: "DCP set vBucket state.",
    0x5C: "DCP noop. The producer sends it, and the consumer must answer or the producer drops the connection.",
    0x5D: "DCP buffer acknowledgement. The producer does not answer. Opaque 0 is the whole connection.",
    0x5E: "DCP control.",
    0x83: "Get Replica. Reads a replica vBucket, usually after the active read timed out.",
    0x89: "Selects the bucket for this connection.",
    0x91: "Checks durability by sequence number.",
    0x92: "Legacy durability check.",
    0x94: "Fetches a document and applies a pessimistic lock.",
    0x95: "Unlocks a previously locked document.",
    0xA0: "Get with meta. Used by cross-datacenter replication.",
    0xA1: "Quiet Get with meta.",
    0xA2: "Set with meta. Used by cross-datacenter replication.",
    0xA3: "Quiet Set with meta.",
    0xA4: "Add with meta.",
    0xA5: "Quiet Add with meta.",
    0xA8: "Delete with meta.",
    0xA9: "Quiet Delete with meta.",
    0xB4: "Pushes an updated cluster map.",
    0xB5: "Pulls the active cluster map.",
    0xC5: "Sub-document Get. Reads one JSON path.",
    0xC6: "Sub-document Exists. Checks one JSON path.",
    0xC7: "Sub-document dictionary add.",
    0xC8: "Sub-document dictionary upsert.",
    0xC9: "Sub-document delete.",
    0xCA: "Sub-document replace.",
    0xCB: "Sub-document array push last.",
    0xCC: "Sub-document array push first.",
    0xCD: "Sub-document array insert.",
    0xCE: "Sub-document array add unique.",
    0xCF: "Sub-document counter.",
    0xD0: "Sub-document multi lookup. Reads several JSON paths.",
    0xD1: "Sub-document multi mutation. Changes several JSON paths.",
    0xD2: "Sub-document get count.",
}


STATUS = {
    0x00: "success",
    0x01: "key not found",
    0x02: "key exists",
    0x03: "value too large",
    0x04: "invalid arguments",
    0x05: "not stored",
    0x06: "non-numeric",
    0x07: "not my vbucket",
    0x08: "authentication error",
    0x09: "locked",
    0x81: "unknown command",
    0x82: "out of memory",
    0x83: "not supported",
    0x84: "internal error",
    0x85: "busy",
    0x86: "temporary failure",
    0x23: "rollback",
}


# DCP is full duplex. The producer sends request-magic packets that are not
# RPCs. kv_engine docs/dcp: the consumer does not reply to stream end, mutation,
# deletion, expiration, or a snapshot marker unless snapshot-type flag 0x08 (Ack)
# is set. Buffer acknowledgement's response is unused. Seqno acknowledged has
# no success response. System event, prepare, commit, abort, seqno advanced,
# OSO snapshot, and cache transfer are producer data. Noop is not in this set:
# the consumer must answer it.
NO_REPLY_OPCODES = {
    0x55, 0x56, 0x57, 0x58, 0x59, 0x5D,
    0x5F, 0x60, 0x61, 0x62, 0x63, 0x64, 0x65, 0x66, 0x67,
}


# Statistics (0x10) answers with one packet per stat line, then an empty
# terminator. Every packet repeats the request opaque. vbucket-seqno does this.
MULTI_RESPONSE_OPCODES = {0x10}
